version: "3.8"
services:
  backend:
    build: ./
    ports:
      - "8081:8080"
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/user_management_application
  database:
    image: postgres:alpine
    environment:
      POSTGRES_DB: user_management_application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"